import { Rarity, Character } from './characters.types';

// lightweight helper to slugify names for expected filenames
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export const CHARACTERS: Character[] = [
  { id: 'yuji', name: 'Yuji Itadori', title: 'Vessel of Sukuna', rarity: 'Grade4', element: 'Taijutsu', hp: 920, atk: 78, def: 62, speed: 88, pullRate: 83.5, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/9/93/Yuji_Itadori_Anime_Portrait.png/revision/latest?cb=20210126213912`, upcoming: false, domain: 'Vessel', skill: { name: 'Divergent Fist', power: 85, desc: 'Fast strike dealing physical + cursed damage.' } },
  { id: 'megumi', name: 'Megumi Fushiguro', title: 'The Ten Shadows', rarity: 'Grade2', element: 'Shadows', hp: 840, atk: 86, def: 58, speed: 80, pullRate: 8, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/6/6e/Megumi_Fushiguro_Anime_Portrait.png/revision/latest?cb=20210126213933`, upcoming: false, domain: 'Shikigami', skill: { name: 'Domain: Body Double', power: 95, desc: 'Summons shikigami to strike targets.' } },
  { id: 'nobara', name: 'Nobara Kugisaki', title: 'Straw Doll Technique', rarity: 'Grade3', element: 'Cursed', hp: 760, atk: 70, def: 50, speed: 82, pullRate: 5, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/b/b8/Nobara_Kugisaki_Anime_Portrait.png/revision/latest?cb=20210126213939`, upcoming: false, domain: 'Straw Doll', skill: { name: 'Resonance Hammer', power: 78, desc: 'Deals piercing curse damage and stuns.' } },
  { id: 'gojo', name: 'Satoru Gojo', title: 'The Honored One', rarity: 'Special', element: 'Limitless', hp: 1100, atk: 120, def: 90, speed: 99, pullRate: 1.5, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/3/31/Satoru_Gojo_Anime_Portrait.png/revision/latest?cb=20210126213941`, upcoming: false, domain: 'Limitless', skill: { name: 'Hollow Purple', power: 200, desc: 'Massive AOE cursed energy obliteration.' } },
  { id: 'nanami', name: 'Kento Nanami', title: 'Ratio Man', rarity: 'Grade2', element: 'Cursed', hp: 880, atk: 84, def: 72, speed: 70, pullRate: 0.5, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/1/10/Kento_Nanami_Anime_Portrait.png/revision/latest?cb=20210126213943`, upcoming: false, domain: 'Ratio', skill: { name: '360 Cut', power: 96, desc: 'Precise strike with damage multiplier.' } },
  { id: 'toji', name: 'Toji Fushiguro', title: 'Sorcerer Killer', rarity: 'Grade1', element: 'Taijutsu', hp: 980, atk: 100, def: 80, speed: 95, pullRate: 0.8, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/25/Toji_Fushiguro_Anime_Portrait.png/revision/latest?cb=20210126214001`, upcoming: false, domain: 'Assassin', skill: { name: 'Inverted Spear', power: 130, desc: 'High damage finisher against sorcerers.' } },
  { id: 'sukuna', name: 'Ryomen Sukuna', title: 'King of Curses', rarity: 'Special', element: 'Cursed', hp: 1300, atk: 135, def: 95, speed: 92, pullRate: 0.2, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/7/70/Sukuna_Anime_Portrait.png/revision/latest?cb=20210126213946`, upcoming: false, domain: 'Cursed King', skill: { name: 'Malevolent Shrine', power: 260, desc: 'Domain that rains cursed slashes.' } },
  { id: 'maki', name: 'Maki Zenin', title: 'Heavenly Restriction', rarity: 'Grade2', element: 'Taijutsu', hp: 900, atk: 88, def: 68, speed: 85, pullRate: 0.3, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/5/5b/Maki_Zenin_Anime_Portrait.png/revision/latest?cb=20210126213947`, upcoming: false, domain: 'Arms', skill: { name: 'Heavenly Swing', power: 102, desc: 'Long reach strike ignoring some defenses.' } },
  { id: 'inumaki', name: 'Toge Inumaki', title: 'Cursed Speech', rarity: 'Grade3', element: 'Cursed', hp: 720, atk: 76, def: 48, speed: 78, pullRate: 0.1, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/7/7a/Toge_Inumaki_Anime_Portrait.png/revision/latest?cb=20210126213949`, upcoming: false, domain: 'Cursed Speech', skill: { name: 'Forbidden Command', power: 110, desc: 'Silence or force target actions.' } },
  { id: 'panda', name: 'Panda', title: 'Intelligent Construct', rarity: 'Grade3', element: 'Neutral', hp: 980, atk: 82, def: 85, speed: 60, pullRate: 0.4, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/4/47/Panda_Anime_Portrait.png/revision/latest?cb=20210126213950`, upcoming: false, domain: 'Construct', skill: { name: 'Bear Slam', power: 94, desc: 'Heavy slam that knocks back enemies.' } },
  { id: 'yuta', name: 'Yuta Okkotsu', title: 'Cursed Hero', rarity: 'Grade1', element: 'Reverse', hp: 1050, atk: 110, def: 88, speed: 86, pullRate: 0.35, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/2/24/Yuta_Okkotsu_Anime_Portrait.png/revision/latest?cb=20210126213952`, upcoming: false, domain: 'Cursed Sword', skill: { name: 'Ritual Slash', power: 140, desc: 'Empowered sword strike from Rika.' } },
  { id: 'mahito', name: 'Mahito', title: 'Idle Transfiguration', rarity: 'Grade1', element: 'Cursed', hp: 1000, atk: 96, def: 70, speed: 84, pullRate: 0.04, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/9/9b/Mahito_Anime_Portrait.png/revision/latest?cb=20210126214000`, upcoming: false, domain: 'Transfiguration', skill: { name: 'Soul Shift', power: 120, desc: 'Malleable curse that alters form.' } },
  { id: 'jogo', name: 'Jogo', title: 'Disaster Flame', rarity: 'Grade1', element: 'Fire', hp: 920, atk: 102, def: 66, speed: 72, pullRate: 0.01, image: `https://static.wikia.nocookie.net/jujutsu-kaisen/images/4/4e/Jogo_Anime_Portrait.png/revision/latest?cb=20210126213955`, upcoming: false, domain: 'Volcanic', skill: { name: 'Lava Burst', power: 118, desc: 'Area fire burst with lingering damage.' } },

  // Examples of characters we don't have images for yet — mark as upcoming
  { id: 'kenjaku', name: 'Kenjaku', title: 'Ancient Vessel', rarity: 'Special', element: 'Cursed', hp: 1250, atk: 130, def: 90, speed: 74, pullRate: 0.2, upcoming: true, domain: 'Manipulation', skill: { name: 'Puppet Master', power: 160, desc: 'Control multiple puppets for damage.' } },
  { id: 'choso', name: 'Choso', title: 'Blood Manipulation', rarity: 'Grade2', element: 'Cursed', hp: 870, atk: 86, def: 60, speed: 79, pullRate: 1.5, upcoming: true, domain: 'Blood Control', skill: { name: 'Blood Spear', power: 98, desc: 'Projectile blood attack.' } },
  { id: 'dagon', name: 'Dagon', title: 'Disaster Tides', rarity: 'Grade1', element: 'Fire', hp: 900, atk: 98, def: 70, speed: 76, pullRate: 0.5, upcoming: true, domain: 'Tidal Curse', skill: { name: 'Tidal Wave', power: 108, desc: 'High impact water/curse attack.' } },
  { id: 'uraume', name: 'Uraume', title: 'Estranged Follower', rarity: 'Grade3', element: 'Cursed', hp: 760, atk: 78, def: 54, speed: 70, pullRate: 0.6, upcoming: true, domain: 'Dark Servant', skill: { name: 'Shadow Bind', power: 74, desc: 'Bind and drain enemy energy.' } },
  { id: 'others', name: 'All Others', title: 'Various', rarity: 'Grade4', element: 'Neutral', hp: 600, atk: 50, def: 40, speed: 50, pullRate: 0.0, upcoming: true, domain: 'Unknown', skill: { name: 'Varied', power: 40, desc: 'Miscellaneous abilities.' } },
];
